FROM ghcr.io/t2linux/fedora-bootc:unstable

RUN \
    dnf group install -y --exclude=rootfiles \
        workstation-product-environment && \ 
    dnf install -y aajohan-comfortaa-fonts && \
    dnf remove -y python3-botocore && \
    dnf clean all
