FROM quay.io/fedora/fedora-silverblue:40

COPY copr-sharpenedblade-t2linux.repo /etc/yum.repos.d/

RUN rpm-ostree override replace --experimental --freeze \
        --from repo="copr:copr.fedorainfracloud.org:sharpenedblade:t2linux" \
        kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra && \
    rpm-ostree install t2linux-repos t2linux-release && \
    ostree container commit
