FROM fedora:38
SHELL ["/usr/bin/bash", "-c"]

RUN dnf install --quiet -y \
    koji \
    git \
    rpmdevtools \
    rpm-sign \
    mock \
    ccache \
    zstd createrepo \
    rpmlint \
    ShellCheck \
&& dnf clean all

COPY mock-defaults.cfg /etc/mock/site-defaults.cfg
