FROM fedora:38
SHELL ["/usr/bin/env", "bash", "-c"]
RUN dnf install -y koji git rpmdevtools rpm-sign mock ccache zstd createrepo rpmlint ShellCheck && \
    dnf clean all && \
    echo -e "config_opts['plugin_conf']['package_state_enable'] = False\nconfig_opts['macros']['_smp_mflags'] = '-j8'\nconfig_opts['plugin_conf']['ccache_opts']['compress'] = True\nconfig_opts['plugin_conf']['root_cache_opts']['compress_program'] = 'zstd'\nconfig_opts['plugin_conf']['root_cache_opts']['extension'] = '.zst'\nconfig_opts['plugin_conf']['hw_info_enable'] = False\n" > /etc/mock/site-defaults.cfg
WORKDIR /repo
