name: Build image 'fedora-ci'
on:
  push:
    branches:
      - f40
    paths:
      - 'fedora-ci/*'
jobs:
  build-image:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-ci"
      tags: 40
      publish: ${{ github.ref == 'refs/heads/f40' }}
      branch: f40
