name: Build image 'fedora-ci'
on:
  push:
    branches:
      - f41
    paths:
      - 'fedora-ci/*'
jobs:
  build-image:
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: "fedora-ci"
      tags: "41"
      publish: ${{ github.ref == 'refs/heads/f41' }}
      branch: f41
